#!/usr/bin/perl

use strict;
use warnings;

#Just placed under version control.

if(@ARGV != 3){
    print "Correct usage is:\nperl compare_cores.pl CorGeneList1 CoreGeneList2 Genome\n\nThe CoreGeneList files are generated by the initJANG.pl program, Genome is the new genome that differs between the supragenome projects\nDying now\n";
    die;
}

#So, we are comparing a smaller (S) to a larger (L) surpagenome cluster
#I'm trying to figure out why core genes are increasing in the mcat21 project
open S, $ARGV[0] or die "Can't open the first (smaller) CoreGenesList: $!";
open L, $ARGV[1] or die "Can't open the second (larger) CoreGenesList: $!";

my $genome = $ARGV[2];

my @s = <S>;
my @l = <L>;

#get rid of newlines
chomp @s;
chomp @l;

my %s_hash;

#create hash of the smaller supragenome project
for my $g (@s){
    $s_hash{$g} = 1;
}

my %already_printed;

my $current_cluster = '';
for my $g (@l){
    if ($g =~ /^>/){
	$current_cluster = $g;
	next;
    }
    elsif ($g =~ /$genome/){
	next;
    }
    elsif (!exists $s_hash{$g} && !exists $already_printed{$current_cluster}){
	print $current_cluster."\n";
	$already_printed{$current_cluster}=1;
    }
}
